### ISSUE TITLE
Remove proposal

### ISSUE THREAD

**Issue by albertvp** [AjuntamentdeBarcelona/decidim.barcelona#315]
### Purpose

A logged user might want to edit or remove a proposal he published.
### Problem

A user cannot remove or unpublish an active proposal.
### Solution

A given user that owns a proposal may edit it first to find a `Remove` button, maybe a confirmation step might be added.

**Comment by albertvp** [comment]
@xabier, following your comments on #316 
do you think that the author shouldn't remove a proposal?
Neither duplicated, or poor supported ones?
I mean, maybe it's not possible to unsay what you proposed last week on the parliament,
but in a digital environment we might allow crud operations or flag it as inactive.
Do we have a mechanism to unpublish deprecated or unsupported proposals?

**Comment by xabier** [comment]
It has be thought carefully. Imagine I don't want taxes on housing
property but I know that many people want that. I make the proposal to
tax housing, it gets plenty of votes. I remove it 2 days before the
final decision is taken. I win!

Duplicates are different, they should be identified in advance, but we
didn't have a comparator engine or AI ready for this at the time, and it
is also good to have that functionality implemented. It is also risky,
because no two proposal will be exactly the same, so merging should
demand a carefull agreement and probably an email should be sent to
anyone that aproved the two proposals for them to re-read the merge and
change their aproval if they don't like the merging.

On 04/03/16 01:23, Albert Vilà Picas wrote:

> @xabier https://github.com/xabier, following your comments on #316
> https://github.com/AjuntamentdeBarcelona/decidim.barcelona/issues/316
> do you think that the author shouldn't remove a proposal?
> Neither duplicated, or poor supported ones?
> I mean, maybe it's not possible to unsay what you proposed last week on
> the parliament,
> but in a digital environment we might allow crud operations or flag it
> as inactive.
> Do we have a mechanism to unpublish deprecated or unsupported proposals?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AjuntamentdeBarcelona/decidim.barcelona/issues/315#issuecomment-192034102.

## 

wget -O - http://sindominio.net/~xabier/xabier.gpg.asc | gpg --import

```
               xabier BARANDIARAN   |  http://www.barandiaran.net
```

"There is no need for fear or hope, but only to look for new weapons"
                                                              DELEUZE
